# Generated by Django 2.1.3 on 2018-12-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_nome', models.CharField(max_length=50, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade_nome', models.CharField(max_length=50, verbose_name='Nome da cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_nome', models.CharField(max_length=50, verbose_name='Nome do país')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_nome', models.CharField(max_length=150, verbose_name='Nome da rua')),
                ('rua_numero', models.CharField(max_length=10, verbose_name='Número')),
                ('rua_complemento', models.CharField(max_length=150, verbose_name='Complemento')),
                ('rua_cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Bairro')),
            ],
            options={
                'verbose_name': 'Rua',
                'verbose_name_plural': 'Ruas',
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_nome', models.CharField(max_length=50, verbose_name='Nome do  estado')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pais')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Uf'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cidade'),
        ),
    ]
