# Generated by Django 2.1.3 on 2018-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='release',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='release',
            name='texto',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
    ]
