# Generated by Django 2.1.3 on 2019-01-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'verbose_name': 'Conteúdo do site', 'verbose_name_plural': 'Conteúdos do site'},
        ),
    ]
