# Generated by Django 2.1.3 on 2018-11-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_nome', models.CharField(max_length=50, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name_plural': 'Bairros',
                'verbose_name': 'Bairro',
            },
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_nome', models.CharField(max_length=150, verbose_name='Nome da rua')),
                ('rua_numero', models.CharField(max_length=10, verbose_name='Número')),
                ('rua_complemento', models.CharField(max_length=150, verbose_name='Complemento')),
                ('rua_cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Bairro')),
            ],
            options={
                'verbose_name_plural': 'Complementos',
                'verbose_name': 'Complemento',
            },
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterField(
            model_name='cidade',
            name='cidade_nome',
            field=models.CharField(max_length=50, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais_nome',
            field=models.CharField(max_length=50, verbose_name='Nome do país'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='uf_nome',
            field=models.CharField(max_length=50, verbose_name='Nome do  estado'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Cidade'),
        ),
    ]
