# Generated by Django 2.1.3 on 2018-11-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cliente_sobrenome', models.CharField(max_length=150, verbose_name='Sobrenome')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua_nome', models.CharField(max_length=150, verbose_name='Nome da rua')),
                ('rua_numero', models.CharField(max_length=10, verbose_name='Número')),
                ('rua_complemento', models.CharField(max_length=150, verbose_name='Complemento')),
                ('rua_cep', models.CharField(max_length=50, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Rua',
                'verbose_name_plural': 'Ruas',
            },
        ),
        migrations.AlterModelOptions(
            name='bairro',
            options={'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AddField(
            model_name='rua',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Rua'),
        ),
    ]
