# Generated by Django 2.1.3 on 2018-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0002_auto_20181126_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_cel_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_estado_civil',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_phone_fixo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone fixo'),
        ),
    ]
