# Generated by Django 2.1.3 on 2018-11-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0003_auto_20181127_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Cliente'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_sobrenome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_sobrnome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrnome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_cel_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_phone_fixo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone fixo'),
        ),
    ]
