# Generated by Django 2.1.3 on 2018-11-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0004_auto_20181127_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
