# Generated by Django 2.1.3 on 2018-11-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0005_auto_20181127_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_cel_phone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_estado_civil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_phone_fixo',
        ),
    ]
