# Generated by Django 2.1.3 on 2018-11-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0006_auto_20181127_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rua',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
