# Generated by Django 2.1.3 on 2018-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0012_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
