# Generated by Django 2.1.3 on 2018-11-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0018_auto_20181127_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cliente_sobrnome', models.CharField(max_length=150, verbose_name='Sobrnome')),
                ('cliente_data_nascimento', models.DateField(verbose_name='Data')),
                ('cliente_estado_civil', models.CharField(max_length=150, verbose_name='Estado civil')),
                ('cliente_email', models.EmailField(max_length=150, verbose_name='Email')),
                ('cliente_phone_fixo', models.CharField(max_length=50, verbose_name='Telefone fixo')),
                ('cliente_cel_phone', models.CharField(max_length=50, verbose_name='Celular')),
                ('cliente_cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Rua')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
