# Generated by Django 2.1.3 on 2018-11-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0019_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa_juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('pj_razao_social', models.CharField(max_length=150, verbose_name='Razão social')),
                ('pj_cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('pj_insc_estadual', models.CharField(max_length=20, verbose_name='Inscrição estadul')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Cliente')),
            ],
            options={
                'verbose_name': 'Pessoa juridica',
                'verbose_name_plural': 'Pessoa juridicas',
            },
        ),
    ]
