# Generated by Django 2.1.3 on 2018-11-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assinaki', '0020_pessoa_juridica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_username', models.CharField(max_length=150, verbose_name='Login')),
                ('login_password', models.CharField(max_length=150, verbose_name='Password')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assinaki.Cliente')),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
            },
        ),
        migrations.AlterModelOptions(
            name='pessoa_juridica',
            options={'verbose_name': 'Pessoa juridica', 'verbose_name_plural': 'Pessoas juridicas'},
        ),
    ]
