# Generated by Django 2.1.3 on 2018-12-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='Assinatura')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Dados_cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Cartão')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('cartao_numero', models.CharField(max_length=50, verbose_name='Número')),
                ('cartao_data', models.DateField(verbose_name='Vencimento em')),
                ('cartao_security_cod', models.CharField(max_length=10, verbose_name='Código de segurança')),
                ('cartao_password', models.CharField(max_length=150, verbose_name='Senha')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Dados do cartao',
                'verbose_name_plural': 'Dados dos cartões',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Documento')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('documento_data', models.DateField(verbose_name='Disponível até')),
                ('documento_quantidade_partes', models.IntegerField(verbose_name='Quantas partes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='PrecoAssinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço base')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Preço base',
                'verbose_name_plural': 'Preços bases',
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.Tipo_documento', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='preco_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.PrecoAssinatura', verbose_name='Preço base'),
        ),
    ]
