# Generated by Django 2.1.3 on 2018-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('cliente_sobrnome', models.CharField(max_length=150, verbose_name='Sobrnome')),
                ('cliente_data_nascimento', models.DateField(verbose_name='Data')),
                ('cliente_estado_civil', models.CharField(max_length=150, verbose_name='Estado civil')),
                ('cliente_email', models.EmailField(max_length=150, verbose_name='Email')),
                ('cliente_phone_fixo', models.CharField(max_length=50, verbose_name='Telefone fixo')),
                ('cliente_cel_phone', models.CharField(max_length=50, verbose_name='Celular')),
                ('cliente_cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Rua', verbose_name='Rua')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_username', models.CharField(max_length=150, verbose_name='Login')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('login_password', models.CharField(max_length=150, verbose_name='Password')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
            },
        ),
        migrations.CreateModel(
            name='Pessoa_juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, verbose_name='Identificador')),
                ('pj_razao_social', models.CharField(max_length=150, verbose_name='Razão social')),
                ('pj_cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('pj_insc_estadual', models.CharField(max_length=20, verbose_name='Inscrição estadul')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pessoa juridica',
                'verbose_name_plural': 'Pessoas juridicas',
            },
        ),
    ]
