# Generated by Django 2.1.3 on 2018-12-11 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_sobrnome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_sobrenome',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='name',
            field=models.CharField(choices=[('CZS', 'Cruzeiro do Sul'), ('RBR', 'Rio Branco'), ('SSA', 'Salvador')], default='SSA', max_length=50, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_estado_civil',
            field=models.CharField(choices=[('SLT', 'Solteira(o)'), ('CSD', 'Casada(o)'), ('DVD', 'Divorciada(o)'), ('SPD', 'Separada'), ('VUV', 'Viúva(o)'), ('UET', 'União estável')], default='SLT', max_length=150, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='name',
            field=models.CharField(choices=[('BR', 'Brasil'), ('AR', 'Argentina')], default='BR', max_length=50, verbose_name='Nome do país'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='name',
            field=models.CharField(choices=[('BA', 'Bahia')], default='BA', max_length=50, verbose_name='Nome do  estado'),
        ),
    ]
