# Generated by Django 2.1.3 on 2019-01-06 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_cartao',
            name='bandeira',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Bandeira do cartão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dados_cartao',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome completo'),
        ),
    ]
